name: 이미지 빌드 & 푸쉬
on:
  push:
    branches: [ 'develop', 'feature/#49' ]
    paths:
      - '.github/workflows/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'src/**'

env:
  ACTIVE_PROFILE: prod

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    name: 이미지 빌드하기

    permissions:
      id-token: write
      contents: read

    steps:
      - name: GitHub 에서 레포 받아오기
        uses: actions/checkout@v3

      - name: JDK17 준비하기
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 도커허브 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Gradle 준비하기
        uses: gradle/gradle-build-action@v2

      - name: 이미지 빌드하고 푸쉬하기
        id: build-image
        run: |
          chmod +x ./gradlew &&
          export IMAGE_TAG=$(git rev-parse --short HEAD) &&
          export IMAGE_NAME=${{ secrets.IMAGE_NAME }} &&
          ./gradlew jib
