name: 이미지 빌드 & 푸쉬
on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths:
      - '.github/workflows/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'src/**'

env:
  SPRING_PROFILES_ACTIVE: prod

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    name: 이미지 빌드하기

    permissions:
      id-token: write
      contents: read

    steps:
      - name: GitHub 에서 레포 받아오기
        uses: actions/checkout@v3

      - name: JDK21 준비하기
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 도커허브 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Gradle 준비하기
        uses: gradle/gradle-build-action@v2

      - name: 이미지 빌드하고 푸쉬하기
        id: build-image
        env:
          GITHUB_SHA: ${{ env.short_commit }}
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          chmod +x ./gradlew
          ./gradlew jib

      - name: 도커 배포하기
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.SSH_PATH }}
            chmod +x ./deploy.sh && ./deploy.sh dev
